### ISSUE TITLE
SIGFPE generated when dividing an integer of type T and value `T::MIN` by `-1`

### ISSUE THREAD

**Issue by ashn-dot-dev** [ashn-dot-dev/sunder#123]
```
import "std";

func main() void {
    var x = s64::MIN / -1;
    std::print_format(std::out(), "{}", (:[]std::formatter)[std::formatter::init[[typeof(x)]](&x)]);
}
```

```sh
$ SUNDER_BACKEND=C SUNDER_CC=clang SUNDER_CFLAGS='-fsanitize=undefined' sunder-run test.sunder
/home/ashn/.sunder/lib/sys/sys.h:235:1: runtime error: division of -9223372036854775808 by -1 cannot be represented in type 'long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/ashn/.sunder/lib/sys/sys.h:235:1 in
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==1970==ERROR: UndefinedBehaviorSanitizer: FPE on unknown address 0x55f76b264d9e (pc 0x55f76b264d9e bp 0x7ffd6da238f0 sp 0x7ffd6da238d0 T1970)
    #0 0x55f76b264d9e in __sunder___div___sunder_s64 a.out.tmp.c
    #1 0x55f76b264c23 in __sunder_main (/home/ashn/sources/sunder/a.out+0x87c23) (BuildId: 0cfc8b686e3880e23910e8e5f589f2df0bc59c02)
    #2 0x55f76b264e8f in main (/home/ashn/sources/sunder/a.out+0x87e8f) (BuildId: 0cfc8b686e3880e23910e8e5f589f2df0bc59c02)
    #3 0x7f5c46ca5d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x7f5c46ca5e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #5 0x55f76b1fb7c4 in _start (/home/ashn/sources/sunder/a.out+0x1e7c4) (BuildId: 0cfc8b686e3880e23910e8e5f589f2df0bc59c02)

UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: FPE a.out.tmp.c in __sunder___div___sunder_s64
==1970==ABORTING
$ SUNDER_BACKEND=nasm sunder-run test.sunder
Floating point exception

**Comment by ashn-dot-dev** [comment]
Fixed in 0dd51c5bb90b55863cc4c81eb3cd45ff322c94ab.
